/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Bender(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/bender.glb");
    const { actions } = useAnimations(animations, group);



    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="Camera"
                    position={[28.921, 0.598, -0.084]}
                    rotation={[1.571, 0.006, -1.58]}
                />
                <mesh
                    name="Antene"
                    castShadow
                    receiveShadow
                    geometry={nodes.Antene.geometry}
                    material={materials["Material.001"]}
                    position={[0.003, 5.073, -0.015]}
                    rotation={[Math.PI, -1.44, Math.PI]}
                    scale={0.082}
                />
                <group
                    name="Head"
                    position={[0.002, 2.632, -0.009]}
                    rotation={[-Math.PI, 1.301, -Math.PI]}
                    scale={[0.608, 0.792, 0.608]}
                >
                    <mesh
                        name="Cylinder003"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003.geometry}
                        material={materials["Material.004"]}
                    />
                    <mesh
                        name="Cylinder003_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003_1.geometry}
                        material={materials["Material.003"]}
                    />
                    <mesh
                        name="Cylinder003_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003_2.geometry}
                        material={materials["Material.002"]}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/bender.glb");
